# Generated by Django 6.0.1 on 2026-01-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_clientprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electricity",
            old_name="monthly_use",
            new_name="meter_value",
        ),
        migrations.RenameField(
            model_name="water",
            old_name="monthly_use",
            new_name="meter_value",
        ),
        migrations.AlterField(
            model_name="electricity",
            name="date",
            field=models.DateField(help_text="Date of electricity reading"),
        ),
        migrations.AlterField(
            model_name="water",
            name="date",
            field=models.DateField(help_text="Date of water reading"),
        ),
        migrations.AlterUniqueTogether(
            name="electricity",
            unique_together={("room", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="water",
            unique_together={("room", "date")},
        ),
        migrations.CreateModel(
            name="UnitPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(help_text="First day of month")),
                (
                    "water_unit_price_eur",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "electricity_unit_price_eur",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "usd_to_eur_rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate USD → EUR",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "unique_together": {("date",)},
            },
        ),
        migrations.CreateModel(
            name="MonthlyBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("room_cost_eur", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "water_cost_eur",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "electricity_cost_eur",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_eur", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "unique_together": {("room", "month")},
            },
        ),
    ]
