# Generated by Django 6.0.1 on 2026-01-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_rename_monthly_use_electricity_meter_value_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="unitprice",
            old_name="usd_to_eur_rate",
            new_name="exchange_rate",
        ),
        migrations.AlterField(
            model_name="electricity",
            name="meter_value",
            field=models.PositiveIntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="electricity_unit_price_eur",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="water_unit_price_eur",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="water",
            name="meter_value",
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
