# Generated by Django 6.0.1 on 2026-01-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_rename_usd_to_eur_rate_unitprice_exchange_rate_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricity",
            options={"ordering": ["date"]},
        ),
        migrations.AlterModelOptions(
            name="water",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="electricity",
            name="is_initial",
            field=models.BooleanField(
                default=False, help_text="Initial meter reading at move-in"
            ),
        ),
        migrations.AddField(
            model_name="water",
            name="is_initial",
            field=models.BooleanField(
                default=False, help_text="Initial meter reading at move-in"
            ),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="meter_value",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="water",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="water",
            name="meter_value",
            field=models.PositiveIntegerField(),
        ),
    ]
