# Generated by Django 6.0.1 on 2026-01-31 21:00

import rooms.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_alter_electricity_options_alter_water_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unitprice",
            name="electricity_unit_price_eur",
        ),
        migrations.RemoveField(
            model_name="unitprice",
            name="water_unit_price_eur",
        ),
        migrations.AddField(
            model_name="unitprice",
            name="electricity_unit_price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name="unitprice",
            name="water_unit_price",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="date",
            field=models.DateField(default=rooms.utils.first_day_of_current_month),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="date",
            field=models.DateField(
                default=rooms.utils.first_day_of_current_month,
                help_text="First day of month",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=4000,
                help_text="Exchange rate USD → KHR",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="date",
            field=models.DateField(default=rooms.utils.first_day_of_current_month),
        ),
    ]
