# Generated by Django 6.0.1 on 2026-01-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0006_remove_unitprice_electricity_unit_price_eur_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlybill",
            old_name="electricity_cost_eur",
            new_name="electricity_cost_khr",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="room_cost_eur",
            new_name="room_cost_khr",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="total_eur",
            new_name="total_khr",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="water_cost_eur",
            new_name="water_cost_khr",
        ),
    ]
