# Generated by Django 6.0.1 on 2026-01-31 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "rooms",
            "0007_rename_electricity_cost_eur_monthlybill_electricity_cost_khr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientprofile",
            name="is_client",
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="enter_date",
            field=models.DateField(blank=True, help_text="Move-in date", null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="exit_date",
            field=models.DateField(blank=True, help_text="Move-out date", null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="id_card_number",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="phone",
            field=models.CharField(max_length=20),
        ),
    ]
