# Generated by Django 6.0.1 on 2026-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_remove_clientprofile_is_client_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
