# Generated by Django 6.0.1 on 2026-02-01 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0009_alter_clientprofile_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="monthlybill",
            old_name="electricity_cost_khr",
            new_name="electricity_cost",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="room_cost_khr",
            new_name="room_cost",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="total_khr",
            new_name="total",
        ),
        migrations.RenameField(
            model_name="monthlybill",
            old_name="water_cost_khr",
            new_name="water_cost",
        ),
    ]
