# Generated by Django 6.0.1 on 2026-02-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "rooms",
            "0010_rename_electricity_cost_khr_monthlybill_electricity_cost_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={"verbose_name": "Tenant", "verbose_name_plural": "Tenants"},
        ),
        migrations.AlterModelOptions(
            name="electricity",
            options={
                "ordering": ["date"],
                "verbose_name_plural": "Electricity Readings",
            },
        ),
        migrations.AlterModelOptions(
            name="monthlybill",
            options={"verbose_name_plural": "Monthly Bills"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="unitprice",
            options={"verbose_name_plural": "Utility Rates"},
        ),
        migrations.AlterModelOptions(
            name="water",
            options={"ordering": ["date"], "verbose_name_plural": "Water Readings"},
        ),
    ]
