# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0014_clientprofile_telegram_chat_id_monthlybill_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlybill",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
