# Generated by Codex on 2026-02-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0015_monthlybill_issued_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlybill",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monthlybill",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
