# Generated by Django 5.2.11 on 2026-02-08 01:02

import django.db.models.deletion
import rooms.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0020_monthlybill_tenant_name_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="electricity",
            options={
                "ordering": ["date"],
                "verbose_name": "Electricity",
                "verbose_name_plural": "Electricity Readings",
            },
        ),
        migrations.AlterModelOptions(
            name="monthlybill",
            options={
                "verbose_name": "Monthly bill",
                "verbose_name_plural": "Monthly Bills",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="unitprice",
            options={
                "verbose_name": "Unit Price",
                "verbose_name_plural": "Utility Rates",
            },
        ),
        migrations.AlterModelOptions(
            name="water",
            options={
                "ordering": ["date"],
                "verbose_name": "Water",
                "verbose_name_plural": "Water Readings",
            },
        ),
        migrations.AlterField(
            model_name="electricity",
            name="date",
            field=models.DateField(
                default=rooms.utils.first_day_of_current_month, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="is_initial",
            field=models.BooleanField(
                default=False,
                help_text="Initial meter reading at move-in",
                verbose_name="Is initial",
            ),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="meter_value",
            field=models.PositiveIntegerField(verbose_name="Meter value"),
        ),
        migrations.AlterField(
            model_name="electricity",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="electricities",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("sent", "Sent"),
                    ("paid", "Paid"),
                ],
                default="draft",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="renter",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Renter",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Room number"
            ),
        ),
        migrations.AlterField(
            model_name="roomhistory",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date"),
        ),
        migrations.AlterField(
            model_name="roomhistory",
            name="renter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="room_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Renter",
            ),
        ),
        migrations.AlterField(
            model_name="roomhistory",
            name="start_date",
            field=models.DateField(verbose_name="Start date"),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="date",
            field=models.DateField(
                default=rooms.utils.first_day_of_current_month,
                help_text="First day of month",
                verbose_name="Date",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="electricity_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                max_digits=10,
                verbose_name="Electricity unit price",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=4000,
                help_text="Exchange rate USD to KHR",
                max_digits=10,
                verbose_name="Exchange rate",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="water_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2000,
                max_digits=10,
                verbose_name="Water unit price",
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="date",
            field=models.DateField(
                default=rooms.utils.first_day_of_current_month, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="is_initial",
            field=models.BooleanField(
                default=False,
                help_text="Initial meter reading at move-in",
                verbose_name="Is initial",
            ),
        ),
        migrations.AlterField(
            model_name="water",
            name="meter_value",
            field=models.PositiveIntegerField(verbose_name="Meter value"),
        ),
        migrations.AlterField(
            model_name="water",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waters",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
    ]
