# Generated by Django 5.2.11 on 2026-02-08 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0022_telegrambatchjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monthlybill",
            name="async_job_pending",
            field=models.BooleanField(default=False, verbose_name="Async job pending"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="async_job_type",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="Async job type"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="data_note",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Data note"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="electricity_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Electricity cost"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="issued_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Issued at"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="last_job_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last job at"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="last_job_message",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Last job message"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="last_job_status",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Last job status"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="month",
            field=models.DateField(verbose_name="Month"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Paid at"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="rooms.room",
                verbose_name="Room",
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="room_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Room cost"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Sent at"),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="tenant_name_snapshot",
            field=models.CharField(
                blank=True,
                default="",
                max_length=150,
                verbose_name="Tenant name snapshot",
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="total",
            field=models.DecimalField(
                decimal_places=2, max_digits=14, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="monthlybill",
            name="water_cost",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Water cost"
            ),
        ),
    ]
