# Generated by Django 5.2.11 on 2026-02-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0023_alter_monthlybill_async_job_pending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricity",
            name="meter_value",
            field=models.PositiveIntegerField(verbose_name="Meter value (kWh)"),
        ),
        migrations.AlterField(
            model_name="water",
            name="meter_value",
            field=models.PositiveIntegerField(verbose_name="Meter value (m³)"),
        ),
    ]
