# Generated by Django 5.2.11 on 2026-02-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0024_alter_electricity_meter_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitprice",
            name="electricity_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                max_digits=10,
                verbose_name="Electricity unit price (៛/kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=6,
                default=4000,
                help_text="Exchange rate USD to KHR",
                max_digits=10,
                verbose_name="Exchange rate (USD→KHR)",
            ),
        ),
        migrations.AlterField(
            model_name="unitprice",
            name="water_unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=2000,
                max_digits=10,
                verbose_name="Water unit price (៛/m³)",
            ),
        ),
    ]
