# Generated by Django 5.2.11 on 2026-02-13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0025_alter_unitprice_electricity_unit_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartAlertLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("month", models.DateField()),
                ("alert_type", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_alerts",
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart alert log",
                "verbose_name_plural": "Smart alert logs",
                "ordering": ["-created_at"],
                "unique_together": {("month", "alert_type", "room")},
            },
        ),
    ]

