"""
Django settings for rentHouseApp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from django.utils.translation import gettext_lazy as _
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-9k#&6u_tjbhjv=_5p!t(5!)^v9gq6-ec$v(z!_g&9d%n^^ic%9",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ASYNC_TASKS = os.getenv("ASYNC_TASKS", "true").lower() == "true"

SESSION_COOKIE_AGE = int(os.getenv("SESSION_COOKIE_AGE", str(30 * 60)))
SESSION_SAVE_EVERY_REQUEST = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Your apps here
    "rooms.apps.RoomsConfig",
]

AUTHENTICATION_BACKENDS = [
    "rooms.backends.UsernameOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "rooms.middleware.DefaultLanguageMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rentHouseApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "rentHouseApp.wsgi.application"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.getenv("JWT_ACCESS_MINUTES", "5"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=int(os.getenv("JWT_REFRESH_DAYS", "7"))),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "km"

TIME_ZONE = "Asia/Phnom_Penh"

USE_I18N = True

USE_TZ = True

FORMAT_MODULE_PATH = ["rentHouseApp.formats"]
USE_THOUSAND_SEPARATOR = True

LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("km", _("Khmer")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Static & media (GCS)
GS_BUCKET_NAME = os.getenv("GS_BUCKET_NAME", "")

STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
MEDIA_URL = STATIC_URL

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {"bucket_name": GS_BUCKET_NAME},
    },
    "staticfiles": {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
        "OPTIONS": {"bucket_name": GS_BUCKET_NAME},
    },
}

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Storage (local only)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
        "OPTIONS": {
            "location": str(MEDIA_ROOT),
            "base_url": MEDIA_URL,
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

CSRF_TRUSTED_ORIGINS = []

# Email settings (for future use)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_HOST = "localhost"
EMAIL_PORT = 1025
EMAIL_USE_TLS = False
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
DEFAULT_FROM_EMAIL = ""
# Currency settings
DEFAULT_CURRENCY = "USD"  # Base currency for rents
TARGET_CURRENCY = "KHR"  # Currency to convert rents into
EXCHANGE_RATE_API_URL = "https://api.exchangerate-api.com/v4/latest/"
EXCHANGE_RATE_API_KEY = ""  # If required by the API provider

# Telegram settings
TELEGRAM_BOT_TOKEN = "8217798129:AAFTRD2XE5lwxdV7-mJIwoPzDxd3j8YcCFU"
TENANTS_TELEGRAM_GROUP_CHAT_ID = -1003826670179
TELEGRAM_TEST_MESSAGE_TEMPLATE = "សួស្តីពីបន្ទប់ជួលគ្រូឌី​ {room_number}."

# Smart Alert
SMART_ALERTS_ENABLED = os.getenv("SMART_ALERTS_ENABLED", "true").lower() == "true"
SMART_ALERT_DUE_DAYS = int(os.getenv("SMART_ALERT_DUE_DAYS", "5"))
SMART_ALERT_USAGE_PCT = float(os.getenv("SMART_ALERT_USAGE_PCT", "30"))

# # PDF generation settings
# PDF_PAGE_SIZE = "A4"
# PDF_FONT = "Helvetica"
# PDF_FONT_SIZE = 12
# PDF_MARGIN = 1 * 72  # 1 inch margin
# INVOICE_TEMPLATE_PATH = BASE_DIR / "rooms" / "templates" / "rooms" / "invoice_template.html"
# INVOICE_OUTPUT_DIR = MEDIA_ROOT / "invoices"

DEFAULT_KH_FONT_PATH = BASE_DIR / "rooms" / "fonts" / "NotoSansKhmer-Regular.ttf"


